import pytest

from sfn_messages.str.types import InstitutionPurpose, PortabilityReturnReason


@pytest.mark.parametrize(
    ('input_value', 'expected_enum'),
    [
        ('FX_INTERBANK_MARKET', InstitutionPurpose.FX_INTERBANK_MARKET),
        ('LAW_8727_REPASSES', InstitutionPurpose.LAW_8727_REPASSES),
        ('SHARED_CASH_TRANSPORT_COST_ALLOCATION', InstitutionPurpose.SHARED_CASH_TRANSPORT_COST_ALLOCATION),
        ('FGHAB_HOUSING_GUARANTEE_FUND_CONTRIBUTION', InstitutionPurpose.FGHAB_HOUSING_GUARANTEE_FUND_CONTRIBUTION),
        (
            'CREDIT_ASSIGNMENT_PRINCIPAL_BY_OWN_ACQUISITION',
            InstitutionPurpose.CREDIT_ASSIGNMENT_PRINCIPAL_BY_OWN_ACQUISITION,
        ),
        ('CREDIT_ASSIGNMENT_CASHFLOW_TRANSFER', InstitutionPurpose.CREDIT_ASSIGNMENT_CASHFLOW_TRANSFER),
        (
            'CREDIT_ASSIGNMENT_ADVANCED_CASHFLOW_TRANSFER',
            InstitutionPurpose.CREDIT_ASSIGNMENT_ADVANCED_CASHFLOW_TRANSFER,
        ),
        ('CREDIT_ASSIGNMENT_MISC_ADJUSTMENTS', InstitutionPurpose.CREDIT_ASSIGNMENT_MISC_ADJUSTMENTS),
        (
            'CREDIT_ASSIGNMENT_INSS_EXCESS_CREDIT_TRANSFER',
            InstitutionPurpose.CREDIT_ASSIGNMENT_INSS_EXCESS_CREDIT_TRANSFER,
        ),
        (
            'CREDIT_ASSIGNMENT_BANK_COOBLIGOR_EXCESS_CREDIT_TRANSFER',
            InstitutionPurpose.CREDIT_ASSIGNMENT_BANK_COOBLIGOR_EXCESS_CREDIT_TRANSFER,
        ),
        ('TCM_SHARED_POUCH_TRANSPORT_SETTLEMENT', InstitutionPurpose.TCM_SHARED_POUCH_TRANSPORT_SETTLEMENT),
        ('VISA_DEBIT_DOMESTIC_CLEARING', InstitutionPurpose.VISA_DEBIT_DOMESTIC_CLEARING),
        ('VISA_CREDIT_DOMESTIC_CLEARING', InstitutionPurpose.VISA_CREDIT_DOMESTIC_CLEARING),
        ('CAPITAL_CONTRIBUTION_INCREASE_OR_REDUCTION', InstitutionPurpose.CAPITAL_CONTRIBUTION_INCREASE_OR_REDUCTION),
        ('PMCMV_HOUSING_PROGRAM_RESOURCES', InstitutionPurpose.PMCMV_HOUSING_PROGRAM_RESOURCES),
        ('CUSTOMER_OWN_INVESTMENT', InstitutionPurpose.CUSTOMER_OWN_INVESTMENT),
        ('CUSTODIAN_REMUNERATION_REFUND', InstitutionPurpose.CUSTODIAN_REMUNERATION_REFUND),
        ('VENDOR_OPERATION_SETTLEMENT', InstitutionPurpose.VENDOR_OPERATION_SETTLEMENT),
        ('OTHER_DEVELOPMENT_BANK_REPASSES', InstitutionPurpose.OTHER_DEVELOPMENT_BANK_REPASSES),
        ('COMPROR_OPERATION_SETTLEMENT', InstitutionPurpose.COMPROR_OPERATION_SETTLEMENT),
        ('PIX_WITHDRAWAL_CHANGE_TIR_PAYMENT', InstitutionPurpose.PIX_WITHDRAWAL_CHANGE_TIR_PAYMENT),
        (
            'CREDIT_ASSIGNMENT_PRINCIPAL_BY_OWN_REPURCHASE',
            InstitutionPurpose.CREDIT_ASSIGNMENT_PRINCIPAL_BY_OWN_REPURCHASE,
        ),
        ('FGC_DPGE_WITH_FIDUCIARY_ALIENATION', InstitutionPurpose.FGC_DPGE_WITH_FIDUCIARY_ALIENATION),
        (
            'CUSTOMER_INVESTMENT_REDEMPTION_TO_OWN_ACCOUNT',
            InstitutionPurpose.CUSTOMER_INVESTMENT_REDEMPTION_TO_OWN_ACCOUNT,
        ),
        ('OFF_SCHEDULE_CLEARING_SYSTEM_POSITION', InstitutionPurpose.OFF_SCHEDULE_CLEARING_SYSTEM_POSITION),
        ('BARCODE_BOLETO_WITH_UNPLANNED_DISCOUNT', InstitutionPurpose.BARCODE_BOLETO_WITH_UNPLANNED_DISCOUNT),
        ('BARCODE_BOLETO_LATE_WITHOUT_CHARGES', InstitutionPurpose.BARCODE_BOLETO_LATE_WITHOUT_CHARGES),
        ('BARCODE_REGISTRY_FEES', InstitutionPurpose.BARCODE_REGISTRY_FEES),
        ('BARCODE_BOLETO_OVERPAID', InstitutionPurpose.BARCODE_BOLETO_OVERPAID),
        ('BNDES_COMMITMENTS_SETTLEMENT', InstitutionPurpose.BNDES_COMMITMENTS_SETTLEMENT),
        ('RCO_STR0026_BOLETO_CLEARING', InstitutionPurpose.RCO_STR0026_BOLETO_CLEARING),
        ('FGCOOP_CONTRIBUTION', InstitutionPurpose.FGCOOP_CONTRIBUTION),
        ('FGCOOP_REFUND_OVERPAID', InstitutionPurpose.FGCOOP_REFUND_OVERPAID),
        ('BNDES_FINAME_REVITALIZA_BONUS_REFUND', InstitutionPurpose.BNDES_FINAME_REVITALIZA_BONUS_REFUND),
        ('BNDES_OVERCHARGED_BOLETO_REFUND', InstitutionPurpose.BNDES_OVERCHARGED_BOLETO_REFUND),
        ('BNDES_FINAME_EQUALIZATION_TRANSFER', InstitutionPurpose.BNDES_FINAME_EQUALIZATION_TRANSFER),
        ('PASEP_PRINCIPAL_AND_EARNINGS_TRANSFER', InstitutionPurpose.PASEP_PRINCIPAL_AND_EARNINGS_TRANSFER),
        ('FTRA_LAND_REFORM_FUNDING_TRANSFER', InstitutionPurpose.FTRA_LAND_REFORM_FUNDING_TRANSFER),
        ('PASEP_APPLYING_AGENT_COMMISSION_TRANSFER', InstitutionPurpose.PASEP_APPLYING_AGENT_COMMISSION_TRANSFER),
        ('CONSUMER_CREDIT_TAX_INCENTIVE', InstitutionPurpose.CONSUMER_CREDIT_TAX_INCENTIVE),
        (
            'OTHER_DEVELOPMENT_BANKS_COMMITMENTS_SETTLEMENT',
            InstitutionPurpose.OTHER_DEVELOPMENT_BANKS_COMMITMENTS_SETTLEMENT,
        ),
        ('RCO_CREDIT_PORTABILITY_COST_REIMBURSEMENT', InstitutionPurpose.RCO_CREDIT_PORTABILITY_COST_REIMBURSEMENT),
        ('FGTS_COLLATERAL_CONSIGNED_CREDIT', InstitutionPurpose.FGTS_COLLATERAL_CONSIGNED_CREDIT),
        ('PIS_PASEP_PAYMENT', InstitutionPurpose.PIS_PASEP_PAYMENT),
        ('FNO_CONSTITUTIONAL_FUND_TRANSFER', InstitutionPurpose.FNO_CONSTITUTIONAL_FUND_TRANSFER),
        ('UNEMPLOYMENT_INSURANCE_PAYMENT', InstitutionPurpose.UNEMPLOYMENT_INSURANCE_PAYMENT),
        ('FGC_LATE_FEES_REGULAR_CONTRIBUTION', InstitutionPurpose.FGC_LATE_FEES_REGULAR_CONTRIBUTION),
        ('FGC_LATE_FEES_DPGE_NO_RECEIVABLES', InstitutionPurpose.FGC_LATE_FEES_DPGE_NO_RECEIVABLES),
        ('FGC_LATE_FEES_DPGE_WITH_RECEIVABLES', InstitutionPurpose.FGC_LATE_FEES_DPGE_WITH_RECEIVABLES),
        ('FGTS_ANNUAL_WITHDRAWALS_FIDUCIARY_TRANSFER', InstitutionPurpose.FGTS_ANNUAL_WITHDRAWALS_FIDUCIARY_TRANSFER),
        ('EMERGENCY_AID_LAW_13982', InstitutionPurpose.EMERGENCY_AID_LAW_13982),
        ('EMERGENCY_EMPLOYMENT_INCOME_BENEFIT', InstitutionPurpose.EMERGENCY_EMPLOYMENT_INCOME_BENEFIT),
        ('FGTS_PORTABILITY_LOAN_DISBURSEMENT', InstitutionPurpose.FGTS_PORTABILITY_LOAN_DISBURSEMENT),
        ('PEAC_EMERGENCY_CREDIT_ACCESS_PROGRAM', InstitutionPurpose.PEAC_EMERGENCY_CREDIT_ACCESS_PROGRAM),
        ('FUNDEB_TRANSFER', InstitutionPurpose.FUNDEB_TRANSFER),
        ('INTERBANK_CREDIT_LINE_COMMITMENT_FEE', InstitutionPurpose.INTERBANK_CREDIT_LINE_COMMITMENT_FEE),
        ('DESENROLA_PROGRAM_OPERATION_PAYMENT', InstitutionPurpose.DESENROLA_PROGRAM_OPERATION_PAYMENT),
        ('MUNICIPAL_TAX_ISS_LCP_157', InstitutionPurpose.MUNICIPAL_TAX_ISS_LCP_157),
        (
            'PRIVATIZATION_MUTUAL_FUND_UNITS_ACQUISITION',
            InstitutionPurpose.PRIVATIZATION_MUTUAL_FUND_UNITS_ACQUISITION,
        ),
        ('MUNICIPAL_TAX_ISS_THIRD_PARTIES_LCP_157', InstitutionPurpose.MUNICIPAL_TAX_ISS_THIRD_PARTIES_LCP_157),
        ('OGU_BUDGET_RESOURCES_DISBURSEMENT', InstitutionPurpose.OGU_BUDGET_RESOURCES_DISBURSEMENT),
        ('MICROFINANCE_GUARANTEE_FUND', InstitutionPurpose.MICROFINANCE_GUARANTEE_FUND),
        ('BACEN_RESOLUTION_98_COMPLIANCE', InstitutionPurpose.BACEN_RESOLUTION_98_COMPLIANCE),
        ('FEDERAL_GOVERNMENT_REPASSES', InstitutionPurpose.FEDERAL_GOVERNMENT_REPASSES),
        ('SPVAT_INDEMNITY_PAYMENT', InstitutionPurpose.SPVAT_INDEMNITY_PAYMENT),
        ('FCA_PAYMENT', InstitutionPurpose.FCA_PAYMENT),
        ('ECO_INVEST_BRASIL_PROGRAM_TRANSFER', InstitutionPurpose.ECO_INVEST_BRASIL_PROGRAM_TRANSFER),
        ('FINAME_RESOURCES_TRANSFER', InstitutionPurpose.FINAME_RESOURCES_TRANSFER),
        ('CONSIGNED_CLT_TRANSFER', InstitutionPurpose.CONSIGNED_CLT_TRANSFER),
        ('COOPERATIVE_CAPITAL_SHARE_REFUND', InstitutionPurpose.COOPERATIVE_CAPITAL_SHARE_REFUND),
        ('SOCIAL_DEVELOPMENT_FUND_UNITS_REDEMPTION', InstitutionPurpose.SOCIAL_DEVELOPMENT_FUND_UNITS_REDEMPTION),
        ('GUARANTEE_FUND_VALUE_MOVEMENT', InstitutionPurpose.GUARANTEE_FUND_VALUE_MOVEMENT),
        ('INTERNATIONAL_TRANSFER_IN_BRL', InstitutionPurpose.INTERNATIONAL_TRANSFER_IN_BRL),
        ('FUTURES_MARKET_POSITION_ADJUSTMENT', InstitutionPurpose.FUTURES_MARKET_POSITION_ADJUSTMENT),
        ('PAYMENTS_TO_BROKERS', InstitutionPurpose.PAYMENTS_TO_BROKERS),
        ('FGTS_LINKED_ACCOUNT_REFUND_HOUSING', InstitutionPurpose.FGTS_LINKED_ACCOUNT_REFUND_HOUSING),
        ('REDECARD_RESOURCES_TRANSFER', InstitutionPurpose.REDECARD_RESOURCES_TRANSFER),
        ('VISANET_RESOURCES_TRANSFER', InstitutionPurpose.VISANET_RESOURCES_TRANSFER),
        ('LAW_8727_INSTALLMENT_PAYMENT', InstitutionPurpose.LAW_8727_INSTALLMENT_PAYMENT),
        ('FAR_LINKED_PROPERTY_MAINTENANCE_EXPENSES', InstitutionPurpose.FAR_LINKED_PROPERTY_MAINTENANCE_EXPENSES),
        (
            'FGTS_FINANCING_OR_LINKED_ACCOUNT_PROPERTY_PAYMENT',
            InstitutionPurpose.FGTS_FINANCING_OR_LINKED_ACCOUNT_PROPERTY_PAYMENT,
        ),
        (
            'FGTS_FINANCING_OR_LINKED_ACCOUNT_PROPERTY_WITH_DEBT_SETTLEMENT',
            InstitutionPurpose.FGTS_FINANCING_OR_LINKED_ACCOUNT_PROPERTY_WITH_DEBT_SETTLEMENT,
        ),
        ('CARDS_CREDIT_DEBIT', InstitutionPurpose.CARDS_CREDIT_DEBIT),
        ('AFRMM_MERCHANT_NAVY_FREIGHT_ADDITIONAL', InstitutionPurpose.AFRMM_MERCHANT_NAVY_FREIGHT_ADDITIONAL),
        (
            'HOUSING_FINANCING_PROPERTY_PAYMENT_OR_DEBT_SETTLEMENT',
            InstitutionPurpose.HOUSING_FINANCING_PROPERTY_PAYMENT_OR_DEBT_SETTLEMENT,
        ),
        ('FX_INTERBANK_FEE', InstitutionPurpose.FX_INTERBANK_FEE),
        ('JUDICIAL_DEPOSIT_WITHDRAWAL', InstitutionPurpose.JUDICIAL_DEPOSIT_WITHDRAWAL),
        ('FINANCIAL_OPERATIONS_SETTLEMENT', InstitutionPurpose.FINANCIAL_OPERATIONS_SETTLEMENT),
        ('ATP_COLLECTION', InstitutionPurpose.ATP_COLLECTION),
        ('FGTS_LINKED_ACCOUNT_WORKER_PAYMENT', InstitutionPurpose.FGTS_LINKED_ACCOUNT_WORKER_PAYMENT),
        ('FGTS_EMPLOYER_PAYMENT_OR_REFUND', InstitutionPurpose.FGTS_EMPLOYER_PAYMENT_OR_REFUND),
        ('PUBLIC_PAYROLL_PAYMENT', InstitutionPurpose.PUBLIC_PAYROLL_PAYMENT),
        ('CREDIT_OPERATION_RELEASE', InstitutionPurpose.CREDIT_OPERATION_RELEASE),
        ('ATM_NETWORK_SHARING_TRANSFER', InstitutionPurpose.ATM_NETWORK_SHARING_TRANSFER),
        ('NETWORK_SHARING_FEES_PAYMENT', InstitutionPurpose.NETWORK_SHARING_FEES_PAYMENT),
        ('RESERVE_TRANSFER_FOR_SCHEDULE_CONTINGENCY', InstitutionPurpose.RESERVE_TRANSFER_FOR_SCHEDULE_CONTINGENCY),
        ('ADMINISTRATIVE_EXPENSE_PAYMENT', InstitutionPurpose.ADMINISTRATIVE_EXPENSE_PAYMENT),
        ('DIVIDENDS_PAYMENT', InstitutionPurpose.DIVIDENDS_PAYMENT),
        ('PAYROLL_DEDUCTION_TRANSFER', InstitutionPurpose.PAYROLL_DEDUCTION_TRANSFER),
        ('SFH_HOUSING_INSURANCE_OPERATIONS', InstitutionPurpose.SFH_HOUSING_INSURANCE_OPERATIONS),
        ('FDS_CAIXA_OPERATIONS', InstitutionPurpose.FDS_CAIXA_OPERATIONS),
        ('SUPPLIER_PAYMENT', InstitutionPurpose.SUPPLIER_PAYMENT),
        ('INVESTOR_CREDIT_TO_CUSTOMER_OF_CREDITED_IF', InstitutionPurpose.INVESTOR_CREDIT_TO_CUSTOMER_OF_CREDITED_IF),
        ('ADMINISTRATION_FEE', InstitutionPurpose.ADMINISTRATION_FEE),
        ('LOTTERY_TRANSFERS_AND_PAYMENTS', InstitutionPurpose.LOTTERY_TRANSFERS_AND_PAYMENTS),
        ('BILATERAL_CLEARING_BOLETO_ADJUSTMENT', InstitutionPurpose.BILATERAL_CLEARING_BOLETO_ADJUSTMENT),
        ('PROEX_RESOURCES_TRANSFER', InstitutionPurpose.PROEX_RESOURCES_TRANSFER),
        ('TED_CONTINGENCY_CHARGES_PAYMENT', InstitutionPurpose.TED_CONTINGENCY_CHARGES_PAYMENT),
        ('FUNDEF_VALUES_TRANSFER', InstitutionPurpose.FUNDEF_VALUES_TRANSFER),
        ('FGC_CREDIT_GUARANTEE_FUND', InstitutionPurpose.FGC_CREDIT_GUARANTEE_FUND),
        ('REGISTRY_EXPENSES_PAYMENT', InstitutionPurpose.REGISTRY_EXPENSES_PAYMENT),
        ('SERVICE_FEE', InstitutionPurpose.SERVICE_FEE),
        ('MERCHANT_PAYMENT', InstitutionPurpose.MERCHANT_PAYMENT),
        ('COURT_SETTLEMENT_OR_EXECUTION_PAYMENT', InstitutionPurpose.COURT_SETTLEMENT_OR_EXECUTION_PAYMENT),
        ('FNE_CONSTITUTIONAL_FUND_TRANSFER', InstitutionPurpose.FNE_CONSTITUTIONAL_FUND_TRANSFER),
        ('LAW_8727_CREDIT_RELEASE', InstitutionPurpose.LAW_8727_CREDIT_RELEASE),
        ('CONTINGENCY_BILATERAL_CLEARING_BOLETOS', InstitutionPurpose.CONTINGENCY_BILATERAL_CLEARING_BOLETOS),
        ('FX_NON_INTERBANK', InstitutionPurpose.FX_NON_INTERBANK),
        ('TECBAN_RESOURCES_TRANSFER', InstitutionPurpose.TECBAN_RESOURCES_TRANSFER),
        ('PAYROLL_SALARY_PAYMENTS', InstitutionPurpose.PAYROLL_SALARY_PAYMENTS),
        ('CONTINGENCY_BILATERAL_CLEARING_ADJUSTMENT', InstitutionPurpose.CONTINGENCY_BILATERAL_CLEARING_ADJUSTMENT),
        ('INCOME_TAX_REFUND', InstitutionPurpose.INCOME_TAX_REFUND),
        ('OPERATIONAL_COST_REIMBURSEMENT_RCO', InstitutionPurpose.OPERATIONAL_COST_REIMBURSEMENT_RCO),
        ('INTEREST_ON_EQUITY_PAYMENT', InstitutionPurpose.INTEREST_ON_EQUITY_PAYMENT),
        (
            'EARNINGS_OR_AMORTIZATION_ON_UNITS_OR_DEBENTURES',
            InstitutionPurpose.EARNINGS_OR_AMORTIZATION_ON_UNITS_OR_DEBENTURES,
        ),
        ('FOREIGN_REMITTANCE_OPERATIONS', InstitutionPurpose.FOREIGN_REMITTANCE_OPERATIONS),
        (
            'GUARANTEE_DEPOSITED_SECURITIES_INTEREST_AMORTIZATION',
            InstitutionPurpose.GUARANTEE_DEPOSITED_SECURITIES_INTEREST_AMORTIZATION,
        ),
        ('REVERSAL_OR_REFUND_MISC', InstitutionPurpose.REVERSAL_OR_REFUND_MISC),
        ('CLEARING_FEES_AND_COSTS', InstitutionPurpose.CLEARING_FEES_AND_COSTS),
        ('COMPENSATION_ADJUSTMENT', InstitutionPurpose.COMPENSATION_ADJUSTMENT),
        ('PROEX_GUARANTEE_FULFILLMENT', InstitutionPurpose.PROEX_GUARANTEE_FULFILLMENT),
        ('WITHHELD_INCOME_TAX_TRANSFER', InstitutionPurpose.WITHHELD_INCOME_TAX_TRANSFER),
        ('TRANSPORT_VOUCHER_PAYMENT', InstitutionPurpose.TRANSPORT_VOUCHER_PAYMENT),
        ('FCO_CONSTITUTIONAL_FUND_TRANSFER', InstitutionPurpose.FCO_CONSTITUTIONAL_FUND_TRANSFER),
        ('STATE_GOVERNMENT_REPASSES', InstitutionPurpose.STATE_GOVERNMENT_REPASSES),
        ('FRAUD_SUSPECT_ADJUSTMENT_BETWEEN_IFS', InstitutionPurpose.FRAUD_SUSPECT_ADJUSTMENT_BETWEEN_IFS),
        ('BILATERAL_CLEARING_SELTEC', InstitutionPurpose.BILATERAL_CLEARING_SELTEC),
        ('BILATERAL_CLEARING_SILOC_CONSOLIDATED', InstitutionPurpose.BILATERAL_CLEARING_SILOC_CONSOLIDATED),
        ('RECEIVABLES_ADVANCE', InstitutionPurpose.RECEIVABLES_ADVANCE),
        ('FGC_DPGE', InstitutionPurpose.FGC_DPGE),
        ('NON_BANK_CORRESPONDENT_TRANSFER', InstitutionPurpose.NON_BANK_CORRESPONDENT_TRANSFER),
        ('SPONSORED_TAX_INCENTIVE_PAYMENT', InstitutionPurpose.SPONSORED_TAX_INCENTIVE_PAYMENT),
        ('DONATION_WITH_TAX_INCENTIVE', InstitutionPurpose.DONATION_WITH_TAX_INCENTIVE),
        ('FGO_OPERATIONS_GUARANTEE_FUND', InstitutionPurpose.FGO_OPERATIONS_GUARANTEE_FUND),
        (
            'SETTLEMENT_ACCOUNT_TO_CURRENT_ACCOUNT_TRANSFER',
            InstitutionPurpose.SETTLEMENT_ACCOUNT_TO_CURRENT_ACCOUNT_TRANSFER,
        ),
        ('FX_SALE_BY_FSB_SOVEREIGN_FUND', InstitutionPurpose.FX_SALE_BY_FSB_SOVEREIGN_FUND),
        ('EMPLOYMENT_TERMINATION_PAYMENT', InstitutionPurpose.EMPLOYMENT_TERMINATION_PAYMENT),
        ('OTHERS', InstitutionPurpose.OTHERS),
    ],
)
def test_institution_purpose_enum(input_value: str, expected_enum: InstitutionPurpose) -> None:
    assert InstitutionPurpose(input_value) == expected_enum


@pytest.mark.parametrize(
    ('input_value', 'expected_enum'),
    [
        (InstitutionPurpose.FX_INTERBANK_MARKET, '1'),
        (InstitutionPurpose.LAW_8727_REPASSES, '10'),
        (InstitutionPurpose.SHARED_CASH_TRANSPORT_COST_ALLOCATION, '100'),
        (InstitutionPurpose.FGHAB_HOUSING_GUARANTEE_FUND_CONTRIBUTION, '101'),
        (InstitutionPurpose.CREDIT_ASSIGNMENT_PRINCIPAL_BY_OWN_ACQUISITION, '102'),
        (InstitutionPurpose.CREDIT_ASSIGNMENT_CASHFLOW_TRANSFER, '105'),
        (InstitutionPurpose.CREDIT_ASSIGNMENT_ADVANCED_CASHFLOW_TRANSFER, '106'),
        (InstitutionPurpose.CREDIT_ASSIGNMENT_MISC_ADJUSTMENTS, '109'),
        (InstitutionPurpose.CREDIT_ASSIGNMENT_INSS_EXCESS_CREDIT_TRANSFER, '110'),
        (InstitutionPurpose.CREDIT_ASSIGNMENT_BANK_COOBLIGOR_EXCESS_CREDIT_TRANSFER, '111'),
        (InstitutionPurpose.TCM_SHARED_POUCH_TRANSPORT_SETTLEMENT, '112'),
        (InstitutionPurpose.VISA_DEBIT_DOMESTIC_CLEARING, '113'),
        (InstitutionPurpose.VISA_CREDIT_DOMESTIC_CLEARING, '114'),
        (InstitutionPurpose.CAPITAL_CONTRIBUTION_INCREASE_OR_REDUCTION, '115'),
        (InstitutionPurpose.PMCMV_HOUSING_PROGRAM_RESOURCES, '116'),
        (InstitutionPurpose.CUSTOMER_OWN_INVESTMENT, '117'),
        (InstitutionPurpose.CUSTODIAN_REMUNERATION_REFUND, '118'),
        (InstitutionPurpose.VENDOR_OPERATION_SETTLEMENT, '119'),
        (InstitutionPurpose.OTHER_DEVELOPMENT_BANK_REPASSES, '12'),
        (InstitutionPurpose.COMPROR_OPERATION_SETTLEMENT, '120'),
        (InstitutionPurpose.PIX_WITHDRAWAL_CHANGE_TIR_PAYMENT, '121'),
        (InstitutionPurpose.CREDIT_ASSIGNMENT_PRINCIPAL_BY_OWN_REPURCHASE, '122'),
        (InstitutionPurpose.FGC_DPGE_WITH_FIDUCIARY_ALIENATION, '123'),
        (InstitutionPurpose.CUSTOMER_INVESTMENT_REDEMPTION_TO_OWN_ACCOUNT, '124'),
        (InstitutionPurpose.OFF_SCHEDULE_CLEARING_SYSTEM_POSITION, '125'),
        (InstitutionPurpose.BARCODE_BOLETO_WITH_UNPLANNED_DISCOUNT, '126'),
        (InstitutionPurpose.BARCODE_BOLETO_LATE_WITHOUT_CHARGES, '127'),
        (InstitutionPurpose.BARCODE_REGISTRY_FEES, '128'),
        (InstitutionPurpose.BARCODE_BOLETO_OVERPAID, '129'),
        (InstitutionPurpose.BNDES_COMMITMENTS_SETTLEMENT, '13'),
        (InstitutionPurpose.RCO_STR0026_BOLETO_CLEARING, '130'),
        (InstitutionPurpose.FGCOOP_CONTRIBUTION, '131'),
        (InstitutionPurpose.FGCOOP_REFUND_OVERPAID, '132'),
        (InstitutionPurpose.BNDES_FINAME_REVITALIZA_BONUS_REFUND, '133'),
        (InstitutionPurpose.BNDES_OVERCHARGED_BOLETO_REFUND, '134'),
        (InstitutionPurpose.BNDES_FINAME_EQUALIZATION_TRANSFER, '135'),
        (InstitutionPurpose.PASEP_PRINCIPAL_AND_EARNINGS_TRANSFER, '136'),
        (InstitutionPurpose.FTRA_LAND_REFORM_FUNDING_TRANSFER, '137'),
        (InstitutionPurpose.PASEP_APPLYING_AGENT_COMMISSION_TRANSFER, '138'),
        (InstitutionPurpose.CONSUMER_CREDIT_TAX_INCENTIVE, '139'),
        (InstitutionPurpose.OTHER_DEVELOPMENT_BANKS_COMMITMENTS_SETTLEMENT, '14'),
        (InstitutionPurpose.RCO_CREDIT_PORTABILITY_COST_REIMBURSEMENT, '140'),
        (InstitutionPurpose.FGTS_COLLATERAL_CONSIGNED_CREDIT, '141'),
        (InstitutionPurpose.PIS_PASEP_PAYMENT, '142'),
        (InstitutionPurpose.FNO_CONSTITUTIONAL_FUND_TRANSFER, '143'),
        (InstitutionPurpose.UNEMPLOYMENT_INSURANCE_PAYMENT, '144'),
        (InstitutionPurpose.FGC_LATE_FEES_REGULAR_CONTRIBUTION, '145'),
        (InstitutionPurpose.FGC_LATE_FEES_DPGE_NO_RECEIVABLES, '146'),
        (InstitutionPurpose.FGC_LATE_FEES_DPGE_WITH_RECEIVABLES, '147'),
        (InstitutionPurpose.FGTS_ANNUAL_WITHDRAWALS_FIDUCIARY_TRANSFER, '148'),
        (InstitutionPurpose.EMERGENCY_AID_LAW_13982, '149'),
        (InstitutionPurpose.EMERGENCY_EMPLOYMENT_INCOME_BENEFIT, '150'),
        (InstitutionPurpose.FGTS_PORTABILITY_LOAN_DISBURSEMENT, '151'),
        (InstitutionPurpose.PEAC_EMERGENCY_CREDIT_ACCESS_PROGRAM, '152'),
        (InstitutionPurpose.FUNDEB_TRANSFER, '153'),
        (InstitutionPurpose.INTERBANK_CREDIT_LINE_COMMITMENT_FEE, '154'),
        (InstitutionPurpose.DESENROLA_PROGRAM_OPERATION_PAYMENT, '155'),
        (InstitutionPurpose.MUNICIPAL_TAX_ISS_LCP_157, '157'),
        (InstitutionPurpose.PRIVATIZATION_MUTUAL_FUND_UNITS_ACQUISITION, '160'),
        (InstitutionPurpose.MUNICIPAL_TAX_ISS_THIRD_PARTIES_LCP_157, '175'),
        (InstitutionPurpose.OGU_BUDGET_RESOURCES_DISBURSEMENT, '176'),
        (InstitutionPurpose.MICROFINANCE_GUARANTEE_FUND, '177'),
        (InstitutionPurpose.BACEN_RESOLUTION_98_COMPLIANCE, '178'),
        (InstitutionPurpose.FEDERAL_GOVERNMENT_REPASSES, '18'),
        (InstitutionPurpose.SPVAT_INDEMNITY_PAYMENT, '180'),
        (InstitutionPurpose.FCA_PAYMENT, '181'),
        (InstitutionPurpose.ECO_INVEST_BRASIL_PROGRAM_TRANSFER, '182'),
        (InstitutionPurpose.FINAME_RESOURCES_TRANSFER, '183'),
        (InstitutionPurpose.CONSIGNED_CLT_TRANSFER, '184'),
        (InstitutionPurpose.COOPERATIVE_CAPITAL_SHARE_REFUND, '185'),
        (InstitutionPurpose.SOCIAL_DEVELOPMENT_FUND_UNITS_REDEMPTION, '19'),
        (InstitutionPurpose.GUARANTEE_FUND_VALUE_MOVEMENT, '20'),
        (InstitutionPurpose.INTERNATIONAL_TRANSFER_IN_BRL, '200'),
        (InstitutionPurpose.FUTURES_MARKET_POSITION_ADJUSTMENT, '201'),
        (InstitutionPurpose.PAYMENTS_TO_BROKERS, '21'),
        (InstitutionPurpose.FGTS_LINKED_ACCOUNT_REFUND_HOUSING, '22'),
        (InstitutionPurpose.REDECARD_RESOURCES_TRANSFER, '23'),
        (InstitutionPurpose.VISANET_RESOURCES_TRANSFER, '24'),
        (InstitutionPurpose.LAW_8727_INSTALLMENT_PAYMENT, '25'),
        (InstitutionPurpose.FAR_LINKED_PROPERTY_MAINTENANCE_EXPENSES, '27'),
        (InstitutionPurpose.FGTS_FINANCING_OR_LINKED_ACCOUNT_PROPERTY_PAYMENT, '28'),
        (InstitutionPurpose.FGTS_FINANCING_OR_LINKED_ACCOUNT_PROPERTY_WITH_DEBT_SETTLEMENT, '29'),
        (InstitutionPurpose.CARDS_CREDIT_DEBIT, '3'),
        (InstitutionPurpose.AFRMM_MERCHANT_NAVY_FREIGHT_ADDITIONAL, '30'),
        (InstitutionPurpose.HOUSING_FINANCING_PROPERTY_PAYMENT_OR_DEBT_SETTLEMENT, '31'),
        (InstitutionPurpose.FX_INTERBANK_FEE, '32'),
        (InstitutionPurpose.JUDICIAL_DEPOSIT_WITHDRAWAL, '33'),
        (InstitutionPurpose.FINANCIAL_OPERATIONS_SETTLEMENT, '34'),
        (InstitutionPurpose.ATP_COLLECTION, '35'),
        (InstitutionPurpose.FGTS_LINKED_ACCOUNT_WORKER_PAYMENT, '36'),
        (InstitutionPurpose.FGTS_EMPLOYER_PAYMENT_OR_REFUND, '37'),
        (InstitutionPurpose.PUBLIC_PAYROLL_PAYMENT, '4'),
        (InstitutionPurpose.CREDIT_OPERATION_RELEASE, '40'),
        (InstitutionPurpose.ATM_NETWORK_SHARING_TRANSFER, '41'),
        (InstitutionPurpose.NETWORK_SHARING_FEES_PAYMENT, '42'),
        (InstitutionPurpose.RESERVE_TRANSFER_FOR_SCHEDULE_CONTINGENCY, '43'),
        (InstitutionPurpose.ADMINISTRATIVE_EXPENSE_PAYMENT, '44'),
        (InstitutionPurpose.DIVIDENDS_PAYMENT, '45'),
        (InstitutionPurpose.PAYROLL_DEDUCTION_TRANSFER, '46'),
        (InstitutionPurpose.SFH_HOUSING_INSURANCE_OPERATIONS, '47'),
        (InstitutionPurpose.FDS_CAIXA_OPERATIONS, '48'),
        (InstitutionPurpose.SUPPLIER_PAYMENT, '5'),
        (InstitutionPurpose.INVESTOR_CREDIT_TO_CUSTOMER_OF_CREDITED_IF, '50'),
        (InstitutionPurpose.ADMINISTRATION_FEE, '53'),
        (InstitutionPurpose.LOTTERY_TRANSFERS_AND_PAYMENTS, '54'),
        (InstitutionPurpose.BILATERAL_CLEARING_BOLETO_ADJUSTMENT, '55'),
        (InstitutionPurpose.PROEX_RESOURCES_TRANSFER, '57'),
        (InstitutionPurpose.TED_CONTINGENCY_CHARGES_PAYMENT, '58'),
        (InstitutionPurpose.FUNDEF_VALUES_TRANSFER, '59'),
        (InstitutionPurpose.FGC_CREDIT_GUARANTEE_FUND, '6'),
        (InstitutionPurpose.REGISTRY_EXPENSES_PAYMENT, '60'),
        (InstitutionPurpose.SERVICE_FEE, '61'),
        (InstitutionPurpose.MERCHANT_PAYMENT, '62'),
        (InstitutionPurpose.COURT_SETTLEMENT_OR_EXECUTION_PAYMENT, '63'),
        (InstitutionPurpose.FNE_CONSTITUTIONAL_FUND_TRANSFER, '64'),
        (InstitutionPurpose.LAW_8727_CREDIT_RELEASE, '66'),
        (InstitutionPurpose.CONTINGENCY_BILATERAL_CLEARING_BOLETOS, '67'),
        (InstitutionPurpose.FX_NON_INTERBANK, '68'),
        (InstitutionPurpose.TECBAN_RESOURCES_TRANSFER, '69'),
        (InstitutionPurpose.PAYROLL_SALARY_PAYMENTS, '70'),
        (InstitutionPurpose.CONTINGENCY_BILATERAL_CLEARING_ADJUSTMENT, '71'),
        (InstitutionPurpose.INCOME_TAX_REFUND, '72'),
        (InstitutionPurpose.OPERATIONAL_COST_REIMBURSEMENT_RCO, '73'),
        (InstitutionPurpose.INTEREST_ON_EQUITY_PAYMENT, '74'),
        (InstitutionPurpose.EARNINGS_OR_AMORTIZATION_ON_UNITS_OR_DEBENTURES, '75'),
        (InstitutionPurpose.FOREIGN_REMITTANCE_OPERATIONS, '76'),
        (InstitutionPurpose.GUARANTEE_DEPOSITED_SECURITIES_INTEREST_AMORTIZATION, '77'),
        (InstitutionPurpose.REVERSAL_OR_REFUND_MISC, '78'),
        (InstitutionPurpose.CLEARING_FEES_AND_COSTS, '79'),
        (InstitutionPurpose.COMPENSATION_ADJUSTMENT, '8'),
        (InstitutionPurpose.PROEX_GUARANTEE_FULFILLMENT, '80'),
        (InstitutionPurpose.WITHHELD_INCOME_TAX_TRANSFER, '81'),
        (InstitutionPurpose.TRANSPORT_VOUCHER_PAYMENT, '82'),
        (InstitutionPurpose.FCO_CONSTITUTIONAL_FUND_TRANSFER, '83'),
        (InstitutionPurpose.STATE_GOVERNMENT_REPASSES, '84'),
        (InstitutionPurpose.FRAUD_SUSPECT_ADJUSTMENT_BETWEEN_IFS, '85'),
        (InstitutionPurpose.BILATERAL_CLEARING_SELTEC, '86'),
        (InstitutionPurpose.BILATERAL_CLEARING_SILOC_CONSOLIDATED, '87'),
        (InstitutionPurpose.RECEIVABLES_ADVANCE, '90'),
        (InstitutionPurpose.FGC_DPGE, '91'),
        (InstitutionPurpose.NON_BANK_CORRESPONDENT_TRANSFER, '92'),
        (InstitutionPurpose.SPONSORED_TAX_INCENTIVE_PAYMENT, '93'),
        (InstitutionPurpose.DONATION_WITH_TAX_INCENTIVE, '94'),
        (InstitutionPurpose.FGO_OPERATIONS_GUARANTEE_FUND, '95'),
        (InstitutionPurpose.SETTLEMENT_ACCOUNT_TO_CURRENT_ACCOUNT_TRANSFER, '96'),
        (InstitutionPurpose.FX_SALE_BY_FSB_SOVEREIGN_FUND, '98'),
        (InstitutionPurpose.EMPLOYMENT_TERMINATION_PAYMENT, '99'),
        (InstitutionPurpose.OTHERS, '99999'),
    ],
)
def test_institution_purpose_values_to_xml_value(input_value: InstitutionPurpose, expected_enum: str) -> None:
    assert input_value.to_xml_value() == expected_enum


@pytest.mark.parametrize(
    ('input_value', 'expected_enum'),
    [
        ('1', InstitutionPurpose.FX_INTERBANK_MARKET),
        ('10', InstitutionPurpose.LAW_8727_REPASSES),
        ('100', InstitutionPurpose.SHARED_CASH_TRANSPORT_COST_ALLOCATION),
        ('101', InstitutionPurpose.FGHAB_HOUSING_GUARANTEE_FUND_CONTRIBUTION),
        ('102', InstitutionPurpose.CREDIT_ASSIGNMENT_PRINCIPAL_BY_OWN_ACQUISITION),
        ('105', InstitutionPurpose.CREDIT_ASSIGNMENT_CASHFLOW_TRANSFER),
        ('106', InstitutionPurpose.CREDIT_ASSIGNMENT_ADVANCED_CASHFLOW_TRANSFER),
        ('109', InstitutionPurpose.CREDIT_ASSIGNMENT_MISC_ADJUSTMENTS),
        ('110', InstitutionPurpose.CREDIT_ASSIGNMENT_INSS_EXCESS_CREDIT_TRANSFER),
        ('111', InstitutionPurpose.CREDIT_ASSIGNMENT_BANK_COOBLIGOR_EXCESS_CREDIT_TRANSFER),
        ('112', InstitutionPurpose.TCM_SHARED_POUCH_TRANSPORT_SETTLEMENT),
        ('113', InstitutionPurpose.VISA_DEBIT_DOMESTIC_CLEARING),
        ('114', InstitutionPurpose.VISA_CREDIT_DOMESTIC_CLEARING),
        ('115', InstitutionPurpose.CAPITAL_CONTRIBUTION_INCREASE_OR_REDUCTION),
        ('116', InstitutionPurpose.PMCMV_HOUSING_PROGRAM_RESOURCES),
        ('117', InstitutionPurpose.CUSTOMER_OWN_INVESTMENT),
        ('118', InstitutionPurpose.CUSTODIAN_REMUNERATION_REFUND),
        ('119', InstitutionPurpose.VENDOR_OPERATION_SETTLEMENT),
        ('12', InstitutionPurpose.OTHER_DEVELOPMENT_BANK_REPASSES),
        ('120', InstitutionPurpose.COMPROR_OPERATION_SETTLEMENT),
        ('121', InstitutionPurpose.PIX_WITHDRAWAL_CHANGE_TIR_PAYMENT),
        ('122', InstitutionPurpose.CREDIT_ASSIGNMENT_PRINCIPAL_BY_OWN_REPURCHASE),
        ('123', InstitutionPurpose.FGC_DPGE_WITH_FIDUCIARY_ALIENATION),
        ('124', InstitutionPurpose.CUSTOMER_INVESTMENT_REDEMPTION_TO_OWN_ACCOUNT),
        ('125', InstitutionPurpose.OFF_SCHEDULE_CLEARING_SYSTEM_POSITION),
        ('126', InstitutionPurpose.BARCODE_BOLETO_WITH_UNPLANNED_DISCOUNT),
        ('127', InstitutionPurpose.BARCODE_BOLETO_LATE_WITHOUT_CHARGES),
        ('128', InstitutionPurpose.BARCODE_REGISTRY_FEES),
        ('129', InstitutionPurpose.BARCODE_BOLETO_OVERPAID),
        ('13', InstitutionPurpose.BNDES_COMMITMENTS_SETTLEMENT),
        ('130', InstitutionPurpose.RCO_STR0026_BOLETO_CLEARING),
        ('131', InstitutionPurpose.FGCOOP_CONTRIBUTION),
        ('132', InstitutionPurpose.FGCOOP_REFUND_OVERPAID),
        ('133', InstitutionPurpose.BNDES_FINAME_REVITALIZA_BONUS_REFUND),
        ('134', InstitutionPurpose.BNDES_OVERCHARGED_BOLETO_REFUND),
        ('135', InstitutionPurpose.BNDES_FINAME_EQUALIZATION_TRANSFER),
        ('136', InstitutionPurpose.PASEP_PRINCIPAL_AND_EARNINGS_TRANSFER),
        ('137', InstitutionPurpose.FTRA_LAND_REFORM_FUNDING_TRANSFER),
        ('138', InstitutionPurpose.PASEP_APPLYING_AGENT_COMMISSION_TRANSFER),
        ('139', InstitutionPurpose.CONSUMER_CREDIT_TAX_INCENTIVE),
        ('14', InstitutionPurpose.OTHER_DEVELOPMENT_BANKS_COMMITMENTS_SETTLEMENT),
        ('140', InstitutionPurpose.RCO_CREDIT_PORTABILITY_COST_REIMBURSEMENT),
        ('141', InstitutionPurpose.FGTS_COLLATERAL_CONSIGNED_CREDIT),
        ('142', InstitutionPurpose.PIS_PASEP_PAYMENT),
        ('143', InstitutionPurpose.FNO_CONSTITUTIONAL_FUND_TRANSFER),
        ('144', InstitutionPurpose.UNEMPLOYMENT_INSURANCE_PAYMENT),
        ('145', InstitutionPurpose.FGC_LATE_FEES_REGULAR_CONTRIBUTION),
        ('146', InstitutionPurpose.FGC_LATE_FEES_DPGE_NO_RECEIVABLES),
        ('147', InstitutionPurpose.FGC_LATE_FEES_DPGE_WITH_RECEIVABLES),
        ('148', InstitutionPurpose.FGTS_ANNUAL_WITHDRAWALS_FIDUCIARY_TRANSFER),
        ('149', InstitutionPurpose.EMERGENCY_AID_LAW_13982),
        ('150', InstitutionPurpose.EMERGENCY_EMPLOYMENT_INCOME_BENEFIT),
        ('151', InstitutionPurpose.FGTS_PORTABILITY_LOAN_DISBURSEMENT),
        ('152', InstitutionPurpose.PEAC_EMERGENCY_CREDIT_ACCESS_PROGRAM),
        ('153', InstitutionPurpose.FUNDEB_TRANSFER),
        ('154', InstitutionPurpose.INTERBANK_CREDIT_LINE_COMMITMENT_FEE),
        ('155', InstitutionPurpose.DESENROLA_PROGRAM_OPERATION_PAYMENT),
        ('157', InstitutionPurpose.MUNICIPAL_TAX_ISS_LCP_157),
        ('160', InstitutionPurpose.PRIVATIZATION_MUTUAL_FUND_UNITS_ACQUISITION),
        ('175', InstitutionPurpose.MUNICIPAL_TAX_ISS_THIRD_PARTIES_LCP_157),
        ('176', InstitutionPurpose.OGU_BUDGET_RESOURCES_DISBURSEMENT),
        ('177', InstitutionPurpose.MICROFINANCE_GUARANTEE_FUND),
        ('178', InstitutionPurpose.BACEN_RESOLUTION_98_COMPLIANCE),
        ('18', InstitutionPurpose.FEDERAL_GOVERNMENT_REPASSES),
        ('180', InstitutionPurpose.SPVAT_INDEMNITY_PAYMENT),
        ('181', InstitutionPurpose.FCA_PAYMENT),
        ('182', InstitutionPurpose.ECO_INVEST_BRASIL_PROGRAM_TRANSFER),
        ('183', InstitutionPurpose.FINAME_RESOURCES_TRANSFER),
        ('184', InstitutionPurpose.CONSIGNED_CLT_TRANSFER),
        ('185', InstitutionPurpose.COOPERATIVE_CAPITAL_SHARE_REFUND),
        ('19', InstitutionPurpose.SOCIAL_DEVELOPMENT_FUND_UNITS_REDEMPTION),
        ('20', InstitutionPurpose.GUARANTEE_FUND_VALUE_MOVEMENT),
        ('200', InstitutionPurpose.INTERNATIONAL_TRANSFER_IN_BRL),
        ('201', InstitutionPurpose.FUTURES_MARKET_POSITION_ADJUSTMENT),
        ('21', InstitutionPurpose.PAYMENTS_TO_BROKERS),
        ('22', InstitutionPurpose.FGTS_LINKED_ACCOUNT_REFUND_HOUSING),
        ('23', InstitutionPurpose.REDECARD_RESOURCES_TRANSFER),
        ('24', InstitutionPurpose.VISANET_RESOURCES_TRANSFER),
        ('25', InstitutionPurpose.LAW_8727_INSTALLMENT_PAYMENT),
        ('27', InstitutionPurpose.FAR_LINKED_PROPERTY_MAINTENANCE_EXPENSES),
        ('28', InstitutionPurpose.FGTS_FINANCING_OR_LINKED_ACCOUNT_PROPERTY_PAYMENT),
        ('29', InstitutionPurpose.FGTS_FINANCING_OR_LINKED_ACCOUNT_PROPERTY_WITH_DEBT_SETTLEMENT),
        ('3', InstitutionPurpose.CARDS_CREDIT_DEBIT),
        ('30', InstitutionPurpose.AFRMM_MERCHANT_NAVY_FREIGHT_ADDITIONAL),
        ('31', InstitutionPurpose.HOUSING_FINANCING_PROPERTY_PAYMENT_OR_DEBT_SETTLEMENT),
        ('32', InstitutionPurpose.FX_INTERBANK_FEE),
        ('33', InstitutionPurpose.JUDICIAL_DEPOSIT_WITHDRAWAL),
        ('34', InstitutionPurpose.FINANCIAL_OPERATIONS_SETTLEMENT),
        ('35', InstitutionPurpose.ATP_COLLECTION),
        ('36', InstitutionPurpose.FGTS_LINKED_ACCOUNT_WORKER_PAYMENT),
        ('37', InstitutionPurpose.FGTS_EMPLOYER_PAYMENT_OR_REFUND),
        ('4', InstitutionPurpose.PUBLIC_PAYROLL_PAYMENT),
        ('40', InstitutionPurpose.CREDIT_OPERATION_RELEASE),
        ('41', InstitutionPurpose.ATM_NETWORK_SHARING_TRANSFER),
        ('42', InstitutionPurpose.NETWORK_SHARING_FEES_PAYMENT),
        ('43', InstitutionPurpose.RESERVE_TRANSFER_FOR_SCHEDULE_CONTINGENCY),
        ('44', InstitutionPurpose.ADMINISTRATIVE_EXPENSE_PAYMENT),
        ('45', InstitutionPurpose.DIVIDENDS_PAYMENT),
        ('46', InstitutionPurpose.PAYROLL_DEDUCTION_TRANSFER),
        ('47', InstitutionPurpose.SFH_HOUSING_INSURANCE_OPERATIONS),
        ('48', InstitutionPurpose.FDS_CAIXA_OPERATIONS),
        ('5', InstitutionPurpose.SUPPLIER_PAYMENT),
        ('50', InstitutionPurpose.INVESTOR_CREDIT_TO_CUSTOMER_OF_CREDITED_IF),
        ('53', InstitutionPurpose.ADMINISTRATION_FEE),
        ('54', InstitutionPurpose.LOTTERY_TRANSFERS_AND_PAYMENTS),
        ('55', InstitutionPurpose.BILATERAL_CLEARING_BOLETO_ADJUSTMENT),
        ('57', InstitutionPurpose.PROEX_RESOURCES_TRANSFER),
        ('58', InstitutionPurpose.TED_CONTINGENCY_CHARGES_PAYMENT),
        ('59', InstitutionPurpose.FUNDEF_VALUES_TRANSFER),
        ('6', InstitutionPurpose.FGC_CREDIT_GUARANTEE_FUND),
        ('60', InstitutionPurpose.REGISTRY_EXPENSES_PAYMENT),
        ('61', InstitutionPurpose.SERVICE_FEE),
        ('62', InstitutionPurpose.MERCHANT_PAYMENT),
        ('63', InstitutionPurpose.COURT_SETTLEMENT_OR_EXECUTION_PAYMENT),
        ('64', InstitutionPurpose.FNE_CONSTITUTIONAL_FUND_TRANSFER),
        ('66', InstitutionPurpose.LAW_8727_CREDIT_RELEASE),
        ('67', InstitutionPurpose.CONTINGENCY_BILATERAL_CLEARING_BOLETOS),
        ('68', InstitutionPurpose.FX_NON_INTERBANK),
        ('69', InstitutionPurpose.TECBAN_RESOURCES_TRANSFER),
        ('70', InstitutionPurpose.PAYROLL_SALARY_PAYMENTS),
        ('71', InstitutionPurpose.CONTINGENCY_BILATERAL_CLEARING_ADJUSTMENT),
        ('72', InstitutionPurpose.INCOME_TAX_REFUND),
        ('73', InstitutionPurpose.OPERATIONAL_COST_REIMBURSEMENT_RCO),
        ('74', InstitutionPurpose.INTEREST_ON_EQUITY_PAYMENT),
        ('75', InstitutionPurpose.EARNINGS_OR_AMORTIZATION_ON_UNITS_OR_DEBENTURES),
        ('76', InstitutionPurpose.FOREIGN_REMITTANCE_OPERATIONS),
        ('77', InstitutionPurpose.GUARANTEE_DEPOSITED_SECURITIES_INTEREST_AMORTIZATION),
        ('78', InstitutionPurpose.REVERSAL_OR_REFUND_MISC),
        ('79', InstitutionPurpose.CLEARING_FEES_AND_COSTS),
        ('8', InstitutionPurpose.COMPENSATION_ADJUSTMENT),
        ('80', InstitutionPurpose.PROEX_GUARANTEE_FULFILLMENT),
        ('81', InstitutionPurpose.WITHHELD_INCOME_TAX_TRANSFER),
        ('82', InstitutionPurpose.TRANSPORT_VOUCHER_PAYMENT),
        ('83', InstitutionPurpose.FCO_CONSTITUTIONAL_FUND_TRANSFER),
        ('84', InstitutionPurpose.STATE_GOVERNMENT_REPASSES),
        ('85', InstitutionPurpose.FRAUD_SUSPECT_ADJUSTMENT_BETWEEN_IFS),
        ('86', InstitutionPurpose.BILATERAL_CLEARING_SELTEC),
        ('87', InstitutionPurpose.BILATERAL_CLEARING_SILOC_CONSOLIDATED),
        ('90', InstitutionPurpose.RECEIVABLES_ADVANCE),
        ('91', InstitutionPurpose.FGC_DPGE),
        ('92', InstitutionPurpose.NON_BANK_CORRESPONDENT_TRANSFER),
        ('93', InstitutionPurpose.SPONSORED_TAX_INCENTIVE_PAYMENT),
        ('94', InstitutionPurpose.DONATION_WITH_TAX_INCENTIVE),
        ('95', InstitutionPurpose.FGO_OPERATIONS_GUARANTEE_FUND),
        ('96', InstitutionPurpose.SETTLEMENT_ACCOUNT_TO_CURRENT_ACCOUNT_TRANSFER),
        ('98', InstitutionPurpose.FX_SALE_BY_FSB_SOVEREIGN_FUND),
        ('99', InstitutionPurpose.EMPLOYMENT_TERMINATION_PAYMENT),
        ('99999', InstitutionPurpose.OTHERS),
    ],
)
def test_institution_purpose_values_from_xml_value(input_value: str, expected_enum: InstitutionPurpose) -> None:
    assert InstitutionPurpose.from_xml_value(input_value) == expected_enum


@pytest.mark.parametrize(
    ('input_value', 'expected_enum'),
    [
        ('fx_interbank_market', InstitutionPurpose.FX_INTERBANK_MARKET),
        ('law_8727_repasses', InstitutionPurpose.LAW_8727_REPASSES),
        ('shared_cash_transport_cost_allocation', InstitutionPurpose.SHARED_CASH_TRANSPORT_COST_ALLOCATION),
        ('fghab_housing_guarantee_fund_contribution', InstitutionPurpose.FGHAB_HOUSING_GUARANTEE_FUND_CONTRIBUTION),
        (
            'credit_assignment_principal_by_own_acquisition',
            InstitutionPurpose.CREDIT_ASSIGNMENT_PRINCIPAL_BY_OWN_ACQUISITION,
        ),
        ('credit_assignment_cashflow_transfer', InstitutionPurpose.CREDIT_ASSIGNMENT_CASHFLOW_TRANSFER),
        (
            'credit_assignment_advanced_cashflow_transfer',
            InstitutionPurpose.CREDIT_ASSIGNMENT_ADVANCED_CASHFLOW_TRANSFER,
        ),
        ('credit_assignment_misc_adjustments', InstitutionPurpose.CREDIT_ASSIGNMENT_MISC_ADJUSTMENTS),
        (
            'credit_assignment_inss_excess_credit_transfer',
            InstitutionPurpose.CREDIT_ASSIGNMENT_INSS_EXCESS_CREDIT_TRANSFER,
        ),
        (
            'credit_assignment_bank_coobligor_excess_credit_transfer',
            InstitutionPurpose.CREDIT_ASSIGNMENT_BANK_COOBLIGOR_EXCESS_CREDIT_TRANSFER,
        ),
        ('tcm_shared_pouch_transport_settlement', InstitutionPurpose.TCM_SHARED_POUCH_TRANSPORT_SETTLEMENT),
        ('visa_debit_domestic_clearing', InstitutionPurpose.VISA_DEBIT_DOMESTIC_CLEARING),
        ('visa_credit_domestic_clearing', InstitutionPurpose.VISA_CREDIT_DOMESTIC_CLEARING),
        ('capital_contribution_increase_or_reduction', InstitutionPurpose.CAPITAL_CONTRIBUTION_INCREASE_OR_REDUCTION),
        ('pmcmv_housing_program_resources', InstitutionPurpose.PMCMV_HOUSING_PROGRAM_RESOURCES),
        ('customer_own_investment', InstitutionPurpose.CUSTOMER_OWN_INVESTMENT),
        ('custodian_remuneration_refund', InstitutionPurpose.CUSTODIAN_REMUNERATION_REFUND),
        ('vendor_operation_settlement', InstitutionPurpose.VENDOR_OPERATION_SETTLEMENT),
        ('other_development_bank_repasses', InstitutionPurpose.OTHER_DEVELOPMENT_BANK_REPASSES),
        ('compror_operation_settlement', InstitutionPurpose.COMPROR_OPERATION_SETTLEMENT),
        ('pix_withdrawal_change_tir_payment', InstitutionPurpose.PIX_WITHDRAWAL_CHANGE_TIR_PAYMENT),
        (
            'credit_assignment_principal_by_own_repurchase',
            InstitutionPurpose.CREDIT_ASSIGNMENT_PRINCIPAL_BY_OWN_REPURCHASE,
        ),
        ('fgc_dpge_with_fiduciary_alienation', InstitutionPurpose.FGC_DPGE_WITH_FIDUCIARY_ALIENATION),
        (
            'customer_investment_redemption_to_own_account',
            InstitutionPurpose.CUSTOMER_INVESTMENT_REDEMPTION_TO_OWN_ACCOUNT,
        ),
        ('off_schedule_clearing_system_position', InstitutionPurpose.OFF_SCHEDULE_CLEARING_SYSTEM_POSITION),
        ('barcode_boleto_with_unplanned_discount', InstitutionPurpose.BARCODE_BOLETO_WITH_UNPLANNED_DISCOUNT),
        ('barcode_boleto_late_without_charges', InstitutionPurpose.BARCODE_BOLETO_LATE_WITHOUT_CHARGES),
        ('barcode_registry_fees', InstitutionPurpose.BARCODE_REGISTRY_FEES),
        ('barcode_boleto_overpaid', InstitutionPurpose.BARCODE_BOLETO_OVERPAID),
        ('bndes_commitments_settlement', InstitutionPurpose.BNDES_COMMITMENTS_SETTLEMENT),
        ('rco_str0026_boleto_clearing', InstitutionPurpose.RCO_STR0026_BOLETO_CLEARING),
        ('fgcoop_contribution', InstitutionPurpose.FGCOOP_CONTRIBUTION),
        ('fgcoop_refund_overpaid', InstitutionPurpose.FGCOOP_REFUND_OVERPAID),
        ('bndes_finame_revitaliza_bonus_refund', InstitutionPurpose.BNDES_FINAME_REVITALIZA_BONUS_REFUND),
        ('bndes_overcharged_boleto_refund', InstitutionPurpose.BNDES_OVERCHARGED_BOLETO_REFUND),
        ('bndes_finame_equalization_transfer', InstitutionPurpose.BNDES_FINAME_EQUALIZATION_TRANSFER),
        ('pasep_principal_and_earnings_transfer', InstitutionPurpose.PASEP_PRINCIPAL_AND_EARNINGS_TRANSFER),
        ('ftra_land_reform_funding_transfer', InstitutionPurpose.FTRA_LAND_REFORM_FUNDING_TRANSFER),
        ('pasep_applying_agent_commission_transfer', InstitutionPurpose.PASEP_APPLYING_AGENT_COMMISSION_TRANSFER),
        ('consumer_credit_tax_incentive', InstitutionPurpose.CONSUMER_CREDIT_TAX_INCENTIVE),
        (
            'other_development_banks_commitments_settlement',
            InstitutionPurpose.OTHER_DEVELOPMENT_BANKS_COMMITMENTS_SETTLEMENT,
        ),
        ('rco_credit_portability_cost_reimbursement', InstitutionPurpose.RCO_CREDIT_PORTABILITY_COST_REIMBURSEMENT),
        ('fgts_collateral_consigned_credit', InstitutionPurpose.FGTS_COLLATERAL_CONSIGNED_CREDIT),
        ('pis_pasep_payment', InstitutionPurpose.PIS_PASEP_PAYMENT),
        ('fno_constitutional_fund_transfer', InstitutionPurpose.FNO_CONSTITUTIONAL_FUND_TRANSFER),
        ('unemployment_insurance_payment', InstitutionPurpose.UNEMPLOYMENT_INSURANCE_PAYMENT),
        ('fgc_late_fees_regular_contribution', InstitutionPurpose.FGC_LATE_FEES_REGULAR_CONTRIBUTION),
        ('fgc_late_fees_dpge_no_receivables', InstitutionPurpose.FGC_LATE_FEES_DPGE_NO_RECEIVABLES),
        ('fgc_late_fees_dpge_with_receivables', InstitutionPurpose.FGC_LATE_FEES_DPGE_WITH_RECEIVABLES),
        ('fgts_annual_withdrawals_fiduciary_transfer', InstitutionPurpose.FGTS_ANNUAL_WITHDRAWALS_FIDUCIARY_TRANSFER),
        ('emergency_aid_law_13982', InstitutionPurpose.EMERGENCY_AID_LAW_13982),
        ('emergency_employment_income_benefit', InstitutionPurpose.EMERGENCY_EMPLOYMENT_INCOME_BENEFIT),
        ('fgts_portability_loan_disbursement', InstitutionPurpose.FGTS_PORTABILITY_LOAN_DISBURSEMENT),
        ('peac_emergency_credit_access_program', InstitutionPurpose.PEAC_EMERGENCY_CREDIT_ACCESS_PROGRAM),
        ('fundeb_transfer', InstitutionPurpose.FUNDEB_TRANSFER),
        ('interbank_credit_line_commitment_fee', InstitutionPurpose.INTERBANK_CREDIT_LINE_COMMITMENT_FEE),
        ('desenrola_program_operation_payment', InstitutionPurpose.DESENROLA_PROGRAM_OPERATION_PAYMENT),
        ('municipal_tax_iss_lcp_157', InstitutionPurpose.MUNICIPAL_TAX_ISS_LCP_157),
        (
            'privatization_mutual_fund_units_acquisition',
            InstitutionPurpose.PRIVATIZATION_MUTUAL_FUND_UNITS_ACQUISITION,
        ),
        ('municipal_tax_iss_third_parties_lcp_157', InstitutionPurpose.MUNICIPAL_TAX_ISS_THIRD_PARTIES_LCP_157),
        ('ogu_budget_resources_disbursement', InstitutionPurpose.OGU_BUDGET_RESOURCES_DISBURSEMENT),
        ('microfinance_guarantee_fund', InstitutionPurpose.MICROFINANCE_GUARANTEE_FUND),
        ('bacen_resolution_98_compliance', InstitutionPurpose.BACEN_RESOLUTION_98_COMPLIANCE),
        ('federal_government_repasses', InstitutionPurpose.FEDERAL_GOVERNMENT_REPASSES),
        ('spvat_indemnity_payment', InstitutionPurpose.SPVAT_INDEMNITY_PAYMENT),
        ('fca_payment', InstitutionPurpose.FCA_PAYMENT),
        ('eco_invest_brasil_program_transfer', InstitutionPurpose.ECO_INVEST_BRASIL_PROGRAM_TRANSFER),
        ('finame_resources_transfer', InstitutionPurpose.FINAME_RESOURCES_TRANSFER),
        ('consigned_clt_transfer', InstitutionPurpose.CONSIGNED_CLT_TRANSFER),
        ('cooperative_capital_share_refund', InstitutionPurpose.COOPERATIVE_CAPITAL_SHARE_REFUND),
        ('social_development_fund_units_redemption', InstitutionPurpose.SOCIAL_DEVELOPMENT_FUND_UNITS_REDEMPTION),
        ('guarantee_fund_value_movement', InstitutionPurpose.GUARANTEE_FUND_VALUE_MOVEMENT),
        ('international_transfer_in_brl', InstitutionPurpose.INTERNATIONAL_TRANSFER_IN_BRL),
        ('futures_market_position_adjustment', InstitutionPurpose.FUTURES_MARKET_POSITION_ADJUSTMENT),
        ('payments_to_brokers', InstitutionPurpose.PAYMENTS_TO_BROKERS),
        ('fgts_linked_account_refund_housing', InstitutionPurpose.FGTS_LINKED_ACCOUNT_REFUND_HOUSING),
        ('redecard_resources_transfer', InstitutionPurpose.REDECARD_RESOURCES_TRANSFER),
        ('visanet_resources_transfer', InstitutionPurpose.VISANET_RESOURCES_TRANSFER),
        ('law_8727_installment_payment', InstitutionPurpose.LAW_8727_INSTALLMENT_PAYMENT),
        ('far_linked_property_maintenance_expenses', InstitutionPurpose.FAR_LINKED_PROPERTY_MAINTENANCE_EXPENSES),
        (
            'fgts_financing_or_linked_account_property_payment',
            InstitutionPurpose.FGTS_FINANCING_OR_LINKED_ACCOUNT_PROPERTY_PAYMENT,
        ),
        (
            'fgts_financing_or_linked_account_property_with_debt_settlement',
            InstitutionPurpose.FGTS_FINANCING_OR_LINKED_ACCOUNT_PROPERTY_WITH_DEBT_SETTLEMENT,
        ),
        ('cards_credit_debit', InstitutionPurpose.CARDS_CREDIT_DEBIT),
        ('afrmm_merchant_navy_freight_additional', InstitutionPurpose.AFRMM_MERCHANT_NAVY_FREIGHT_ADDITIONAL),
        (
            'housing_financing_property_payment_or_debt_settlement',
            InstitutionPurpose.HOUSING_FINANCING_PROPERTY_PAYMENT_OR_DEBT_SETTLEMENT,
        ),
        ('fx_interbank_fee', InstitutionPurpose.FX_INTERBANK_FEE),
        ('judicial_deposit_withdrawal', InstitutionPurpose.JUDICIAL_DEPOSIT_WITHDRAWAL),
        ('financial_operations_settlement', InstitutionPurpose.FINANCIAL_OPERATIONS_SETTLEMENT),
        ('atp_collection', InstitutionPurpose.ATP_COLLECTION),
        ('fgts_linked_account_worker_payment', InstitutionPurpose.FGTS_LINKED_ACCOUNT_WORKER_PAYMENT),
        ('fgts_employer_payment_or_refund', InstitutionPurpose.FGTS_EMPLOYER_PAYMENT_OR_REFUND),
        ('public_payroll_payment', InstitutionPurpose.PUBLIC_PAYROLL_PAYMENT),
        ('credit_operation_release', InstitutionPurpose.CREDIT_OPERATION_RELEASE),
        ('atm_network_sharing_transfer', InstitutionPurpose.ATM_NETWORK_SHARING_TRANSFER),
        ('network_sharing_fees_payment', InstitutionPurpose.NETWORK_SHARING_FEES_PAYMENT),
        ('reserve_transfer_for_schedule_contingency', InstitutionPurpose.RESERVE_TRANSFER_FOR_SCHEDULE_CONTINGENCY),
        ('administrative_expense_payment', InstitutionPurpose.ADMINISTRATIVE_EXPENSE_PAYMENT),
        ('dividends_payment', InstitutionPurpose.DIVIDENDS_PAYMENT),
        ('payroll_deduction_transfer', InstitutionPurpose.PAYROLL_DEDUCTION_TRANSFER),
        ('sfh_housing_insurance_operations', InstitutionPurpose.SFH_HOUSING_INSURANCE_OPERATIONS),
        ('fds_caixa_operations', InstitutionPurpose.FDS_CAIXA_OPERATIONS),
        ('supplier_payment', InstitutionPurpose.SUPPLIER_PAYMENT),
        ('investor_credit_to_customer_of_credited_if', InstitutionPurpose.INVESTOR_CREDIT_TO_CUSTOMER_OF_CREDITED_IF),
        ('administration_fee', InstitutionPurpose.ADMINISTRATION_FEE),
        ('lottery_transfers_and_payments', InstitutionPurpose.LOTTERY_TRANSFERS_AND_PAYMENTS),
        ('bilateral_clearing_boleto_adjustment', InstitutionPurpose.BILATERAL_CLEARING_BOLETO_ADJUSTMENT),
        ('proex_resources_transfer', InstitutionPurpose.PROEX_RESOURCES_TRANSFER),
        ('ted_contingency_charges_payment', InstitutionPurpose.TED_CONTINGENCY_CHARGES_PAYMENT),
        ('fundef_values_transfer', InstitutionPurpose.FUNDEF_VALUES_TRANSFER),
        ('fgc_credit_guarantee_fund', InstitutionPurpose.FGC_CREDIT_GUARANTEE_FUND),
        ('registry_expenses_payment', InstitutionPurpose.REGISTRY_EXPENSES_PAYMENT),
        ('service_fee', InstitutionPurpose.SERVICE_FEE),
        ('merchant_payment', InstitutionPurpose.MERCHANT_PAYMENT),
        ('court_settlement_or_execution_payment', InstitutionPurpose.COURT_SETTLEMENT_OR_EXECUTION_PAYMENT),
        ('fne_constitutional_fund_transfer', InstitutionPurpose.FNE_CONSTITUTIONAL_FUND_TRANSFER),
        ('law_8727_credit_release', InstitutionPurpose.LAW_8727_CREDIT_RELEASE),
        ('contingency_bilateral_clearing_boletos', InstitutionPurpose.CONTINGENCY_BILATERAL_CLEARING_BOLETOS),
        ('fx_non_interbank', InstitutionPurpose.FX_NON_INTERBANK),
        ('tecban_resources_transfer', InstitutionPurpose.TECBAN_RESOURCES_TRANSFER),
        ('payroll_salary_payments', InstitutionPurpose.PAYROLL_SALARY_PAYMENTS),
        ('contingency_bilateral_clearing_adjustment', InstitutionPurpose.CONTINGENCY_BILATERAL_CLEARING_ADJUSTMENT),
        ('income_tax_refund', InstitutionPurpose.INCOME_TAX_REFUND),
        ('operational_cost_reimbursement_rco', InstitutionPurpose.OPERATIONAL_COST_REIMBURSEMENT_RCO),
        ('interest_on_equity_payment', InstitutionPurpose.INTEREST_ON_EQUITY_PAYMENT),
        (
            'earnings_or_amortization_on_units_or_debentures',
            InstitutionPurpose.EARNINGS_OR_AMORTIZATION_ON_UNITS_OR_DEBENTURES,
        ),
        ('foreign_remittance_operations', InstitutionPurpose.FOREIGN_REMITTANCE_OPERATIONS),
        (
            'guarantee_deposited_securities_interest_amortization',
            InstitutionPurpose.GUARANTEE_DEPOSITED_SECURITIES_INTEREST_AMORTIZATION,
        ),
        ('reversal_or_refund_misc', InstitutionPurpose.REVERSAL_OR_REFUND_MISC),
        ('clearing_fees_and_costs', InstitutionPurpose.CLEARING_FEES_AND_COSTS),
        ('compensation_adjustment', InstitutionPurpose.COMPENSATION_ADJUSTMENT),
        ('proex_guarantee_fulfillment', InstitutionPurpose.PROEX_GUARANTEE_FULFILLMENT),
        ('withheld_income_tax_transfer', InstitutionPurpose.WITHHELD_INCOME_TAX_TRANSFER),
        ('transport_voucher_payment', InstitutionPurpose.TRANSPORT_VOUCHER_PAYMENT),
        ('fco_constitutional_fund_transfer', InstitutionPurpose.FCO_CONSTITUTIONAL_FUND_TRANSFER),
        ('state_government_repasses', InstitutionPurpose.STATE_GOVERNMENT_REPASSES),
        ('fraud_suspect_adjustment_between_ifs', InstitutionPurpose.FRAUD_SUSPECT_ADJUSTMENT_BETWEEN_IFS),
        ('bilateral_clearing_seltec', InstitutionPurpose.BILATERAL_CLEARING_SELTEC),
        ('bilateral_clearing_siloc_consolidated', InstitutionPurpose.BILATERAL_CLEARING_SILOC_CONSOLIDATED),
        ('receivables_advance', InstitutionPurpose.RECEIVABLES_ADVANCE),
        ('fgc_dpge', InstitutionPurpose.FGC_DPGE),
        ('non_bank_correspondent_transfer', InstitutionPurpose.NON_BANK_CORRESPONDENT_TRANSFER),
        ('sponsored_tax_incentive_payment', InstitutionPurpose.SPONSORED_TAX_INCENTIVE_PAYMENT),
        ('donation_with_tax_incentive', InstitutionPurpose.DONATION_WITH_TAX_INCENTIVE),
        ('fgo_operations_guarantee_fund', InstitutionPurpose.FGO_OPERATIONS_GUARANTEE_FUND),
        (
            'settlement_account_to_current_account_transfer',
            InstitutionPurpose.SETTLEMENT_ACCOUNT_TO_CURRENT_ACCOUNT_TRANSFER,
        ),
        ('fx_sale_by_fsb_sovereign_fund', InstitutionPurpose.FX_SALE_BY_FSB_SOVEREIGN_FUND),
        ('employment_termination_payment', InstitutionPurpose.EMPLOYMENT_TERMINATION_PAYMENT),
        ('others', InstitutionPurpose.OTHERS),
    ],
)
def test_institution_purpose_accepts_case_insensitive_values(
    input_value: str, expected_enum: InstitutionPurpose
) -> None:
    assert InstitutionPurpose(input_value) == expected_enum


@pytest.mark.parametrize(
    'invalid_value',
    [
        'invalid_purpose',  # Completely invalid string
        '123456',  # Numeric string
        'fx-interbank-market',  # Invalid abbreviation
    ],
)
def test_institution_purpose_rejects_invalid_values(invalid_value: str) -> None:
    with pytest.raises(ValueError, match=invalid_value):
        InstitutionPurpose(invalid_value)


@pytest.mark.parametrize(
    ('input_value', 'expected_enum'),
    [
        ('DESTINATION_ACCOUNT_CLOSED', PortabilityReturnReason.DESTINATION_ACCOUNT_CLOSED),
        ('INVALID_DESTINATION_AGENCY_OR_ACCOUNT', PortabilityReturnReason.INVALID_DESTINATION_AGENCY_OR_ACCOUNT),
        ('PORTABILITY_NOT_FOUND', PortabilityReturnReason.PORTABILITY_NOT_FOUND),
        ('PORTABILITY_REFUSED_AMOUNT_MISMATCH', PortabilityReturnReason.PORTABILITY_REFUSED_AMOUNT_MISMATCH),
        ('PORTABILITY_HELD_BY_ORIGINAL_CREDITOR', PortabilityReturnReason.PORTABILITY_HELD_BY_ORIGINAL_CREDITOR),
        (
            'PORTABILITY_SETTLED_MORE_THAN_ONCE_STR0047',
            PortabilityReturnReason.PORTABILITY_SETTLED_MORE_THAN_ONCE_STR0047,
        ),
        ('PAYMENT_ON_INVALID_DATE', PortabilityReturnReason.PAYMENT_ON_INVALID_DATE),
        (
            'PORTABILITY_ALREADY_SETTLED_BY_ORIGINAL_CREDITOR',
            PortabilityReturnReason.PORTABILITY_ALREADY_SETTLED_BY_ORIGINAL_CREDITOR,
        ),
    ],
)
def test_portability_return_reason_accepts_exact_values(
    input_value: str, expected_enum: PortabilityReturnReason
) -> None:
    assert PortabilityReturnReason(input_value) == expected_enum


@pytest.mark.parametrize(
    ('input_value', 'expected_enum'),
    [
        (PortabilityReturnReason.DESTINATION_ACCOUNT_CLOSED, '1'),
        (PortabilityReturnReason.INVALID_DESTINATION_AGENCY_OR_ACCOUNT, '2'),
        (PortabilityReturnReason.PORTABILITY_NOT_FOUND, '78'),
        (PortabilityReturnReason.PORTABILITY_REFUSED_AMOUNT_MISMATCH, '79'),
        (PortabilityReturnReason.PORTABILITY_HELD_BY_ORIGINAL_CREDITOR, '81'),
        (PortabilityReturnReason.PORTABILITY_SETTLED_MORE_THAN_ONCE_STR0047, '82'),
        (PortabilityReturnReason.PAYMENT_ON_INVALID_DATE, '83'),
        (PortabilityReturnReason.PORTABILITY_ALREADY_SETTLED_BY_ORIGINAL_CREDITOR, '84'),
    ],
)
def test_portability_return_reason_values_to_xml_value(
    input_value: PortabilityReturnReason, expected_enum: str
) -> None:
    assert input_value.to_xml_value() == expected_enum


@pytest.mark.parametrize(
    ('input_value', 'expected_enum'),
    [
        ('1', PortabilityReturnReason.DESTINATION_ACCOUNT_CLOSED),
        ('2', PortabilityReturnReason.INVALID_DESTINATION_AGENCY_OR_ACCOUNT),
        ('78', PortabilityReturnReason.PORTABILITY_NOT_FOUND),
        ('79', PortabilityReturnReason.PORTABILITY_REFUSED_AMOUNT_MISMATCH),
        ('81', PortabilityReturnReason.PORTABILITY_HELD_BY_ORIGINAL_CREDITOR),
        ('82', PortabilityReturnReason.PORTABILITY_SETTLED_MORE_THAN_ONCE_STR0047),
        ('83', PortabilityReturnReason.PAYMENT_ON_INVALID_DATE),
        ('84', PortabilityReturnReason.PORTABILITY_ALREADY_SETTLED_BY_ORIGINAL_CREDITOR),
    ],
)
def test_portability_return_reason_values_from_xml_value(
    input_value: str, expected_enum: PortabilityReturnReason
) -> None:
    assert PortabilityReturnReason.from_xml_value(input_value) == expected_enum


@pytest.mark.parametrize(
    ('input_value', 'expected_enum'),
    [
        ('destination_account_closed', PortabilityReturnReason.DESTINATION_ACCOUNT_CLOSED),
        ('invalid_destination_agency_or_account', PortabilityReturnReason.INVALID_DESTINATION_AGENCY_OR_ACCOUNT),
        ('portability_not_found', PortabilityReturnReason.PORTABILITY_NOT_FOUND),
        ('portability_refused_amount_mismatch', PortabilityReturnReason.PORTABILITY_REFUSED_AMOUNT_MISMATCH),
        ('portability_held_by_original_creditor', PortabilityReturnReason.PORTABILITY_HELD_BY_ORIGINAL_CREDITOR),
        (
            'portability_settled_more_than_once_str0047',
            PortabilityReturnReason.PORTABILITY_SETTLED_MORE_THAN_ONCE_STR0047,
        ),
        ('payment_on_invalid_date', PortabilityReturnReason.PAYMENT_ON_INVALID_DATE),
        (
            'portability_already_settled_by_original_creditor',
            PortabilityReturnReason.PORTABILITY_ALREADY_SETTLED_BY_ORIGINAL_CREDITOR,
        ),
    ],
)
def test_portability_return_reason_accepts_case_insensitive_values(
    input_value: str, expected_enum: PortabilityReturnReason
) -> None:
    assert PortabilityReturnReason(input_value) == expected_enum


@pytest.mark.parametrize(
    'input_value',
    [
        'invalid_reason',  # Completely invalid string
        '123',  # Numeric string
        'destination-account-closed',  # Invalid abbreviation
    ],
)
def test_portability_return_reason_rejects_invalid_values(input_value: str) -> None:
    with pytest.raises(ValueError, match=input_value):
        PortabilityReturnReason(input_value)
